 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/oauth_configs", type: :request do
  # OAuthConfig. As you add validations to OAuthConfig, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OAuthConfig.create! valid_attributes
      get oauth_configs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      oauth_config = OAuthConfig.create! valid_attributes
      get oauth_config_url(oauth_config)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_oauth_config_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      oauth_config = OAuthConfig.create! valid_attributes
      get edit_oauth_config_url(oauth_config)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OAuthConfig" do
        expect {
          post oauth_configs_url, params: { oauth_config: valid_attributes }
        }.to change(OAuthConfig, :count).by(1)
      end

      it "redirects to the created oauth_config" do
        post oauth_configs_url, params: { oauth_config: valid_attributes }
        expect(response).to redirect_to(oauth_config_url(OAuthConfig.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OAuthConfig" do
        expect {
          post oauth_configs_url, params: { oauth_config: invalid_attributes }
        }.to change(OAuthConfig, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post oauth_configs_url, params: { oauth_config: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested oauth_config" do
        oauth_config = OAuthConfig.create! valid_attributes
        patch oauth_config_url(oauth_config), params: { oauth_config: new_attributes }
        oauth_config.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the oauth_config" do
        oauth_config = OAuthConfig.create! valid_attributes
        patch oauth_config_url(oauth_config), params: { oauth_config: new_attributes }
        oauth_config.reload
        expect(response).to redirect_to(oauth_config_url(oauth_config))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        oauth_config = OAuthConfig.create! valid_attributes
        patch oauth_config_url(oauth_config), params: { oauth_config: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested oauth_config" do
      oauth_config = OAuthConfig.create! valid_attributes
      expect {
        delete oauth_config_url(oauth_config)
      }.to change(OAuthConfig, :count).by(-1)
    end

    it "redirects to the oauth_configs list" do
      oauth_config = OAuthConfig.create! valid_attributes
      delete oauth_config_url(oauth_config)
      expect(response).to redirect_to(oauth_configs_url)
    end
  end
end
